language: java
jdk:
  - oraclejdk8
branches:
  only:
  - master
cache:
  directories:
  - .autoconf
  - $HOME/.m2
before_install:
  - "echo skipped"
install:
  - "echo skipped"
script:
  - cd grpc-java-spring
  - mvn clean package
after_success:
  - "echo skipped"
